# Generated by Django 2.2.7 on 2019-11-13 01:31

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(default='Men', max_length=32)),
                ('description', models.CharField(default='', max_length=128)),
                ('photo', models.CharField(default='images/', max_length=32, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verification_status', models.IntegerField(default=0, null=True)),
                ('street1', models.CharField(default='', max_length=128)),
                ('street2', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(default='', max_length=32)),
                ('state', models.CharField(choices=[('NJ', 'Newjersey')], default='', max_length=2)),
                ('zip_code', models.CharField(default='', help_text='Zip code must be in XXXXX, 5 digit format', max_length=5)),
                ('profile_filled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(help_text="Phone number must be entered in the format: 'XXX-XXX-XXXX'. Up to 15 digits allowed.", max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'XXX-XXX-XXXX'. Up to 15 digits allowed.", regex='^[2-9]\\d{2}-\\d{3}-\\d{4}$')])),
                ('phone_verification_code', models.IntegerField(default=0)),
                ('phone_verification_status', models.IntegerField(default=0)),
                ('number_of_sms_sent', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('customer_id', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('position', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('type', models.CharField(help_text='Service type', max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mysite.Profile')),
                ('supporting_zip_codes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('rating', models.IntegerField(null=True)),
                ('pricing', models.IntegerField(null=True)),
                ('hours', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('delivery_notes', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('services', models.CharField(blank=True, max_length=512, null=True)),
                ('photo', models.CharField(default='images/shop/', max_length=32, null=True)),
                ('customers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('delivered', models.BooleanField(default=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('OR', 'Order Received'), ('PS', 'Pickup Scheduled'), ('PU', 'Picked Up and In Process'), ('DS', 'Delivery Scheduled'), ('DV', 'Delivered')], default='', max_length=2, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('price_confirmed', models.BooleanField(default=False, null=True)),
                ('order_disabled', models.BooleanField(default=False, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Profile')),
                ('item', models.ManyToManyField(to='mysite.Item')),
                ('service', models.ManyToManyField(to='mysite.Service')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Vendor'),
        ),
    ]
