# Generated by Django 2.1.2 on 2019-08-21 16:38

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(default='Men', max_length=32)),
                ('description', models.CharField(default='', max_length=128)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date',
                 models.DateField(default=datetime.datetime(2019, 9, 20, 16, 38, 45, 583882, tzinfo=utc), null=True)),
                ('number', models.IntegerField(default=0, help_text='Number of items sold')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verification_status', models.IntegerField(default=0, null=True)),
                ('street1', models.CharField(default='', max_length=128)),
                ('street2', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(default='', max_length=32)),
                ('state', models.CharField(default='', max_length=10)),
                ('zip_code', models.CharField(default=0, max_length=12)),
                ('birth_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('profile_filled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(help_text='Phone format is: 123-456-7890', max_length=17, validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: 'XXX-XXX-XXXX'. Up to 15 digits allowed.",
                        regex='^[2-9]\\d{2}-\\d{3}-\\d{4}$')])),
                ('phone_verification_status', models.IntegerField(default=0)),
                ('number_of_sms_sent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('type', models.CharField(help_text='Service type', max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Profile')),
                ('item', models.ManyToManyField(to='core.Item')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='core.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(to='core.Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vendor'),
        ),
    ]
