# Generated by Django 2.1.2 on 2019-08-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_email_verification',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
