# Generated by Django 2.1.2 on 2019-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('type', models.CharField(help_text='Service type', max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='service',
            field=models.ManyToManyField(to='core.Service'),
        ),
    ]
