# Generated by Django 2.1.2 on 2019-08-21 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20190821_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 20, 16, 55, 27, 557708, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.AutoField(default=100000, primary_key=True, serialize=False),
        ),
    ]
