# Generated by Django 2.1.2 on 2019-08-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
