# Generated by Django 2.1.2 on 2019-08-21 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20190821_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_status',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 20, 19, 24, 54, 513288, tzinfo=utc), null=True),
        ),
    ]
