# Generated by Django 2.1.2 on 2019-08-21 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20190821_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 20, 19, 56, 53, 430414, tzinfo=utc), null=True),
        ),
    ]
