# Generated by Django 2.1.2 on 2019-08-23 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20190821_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 13, 58, 37, 740221, tzinfo=utc), null=True),
        ),
    ]
