# Generated by Django 2.1.2 on 2019-08-23 20:40

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20190823_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_verification_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 20, 40, 2, 41708, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(
                help_text="Phone number must be entered in the format: 'XXX-XXX-XXXX'. Up to 15 digits allowed.",
                max_length=17, validators=[django.core.validators.RegexValidator(
                    message="Phone number must be entered in the format: 'XXX-XXX-XXXX'. Up to 15 digits allowed.",
                    regex='^[2-9]\\d{2}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='00000', max_length=12),
        ),
    ]
