# Generated by Django 2.1.2 on 2019-08-26 01:18

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190823_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 1, 18, 45, 192367, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
