# Generated by Django 2.1.2 on 2019-08-29 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190829_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 28, 12, 41, 1, 351691, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='', help_text='Zip code must be in XXXXX, 5 digit format', max_length=12),
        ),
    ]
