# Generated by Django 2.1.2 on 2019-08-30 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_auto_20190829_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 29, 14, 30, 10, 342235, tzinfo=utc), null=True),
        ),
    ]
