# Generated by Django 2.1.2 on 2019-09-03 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_auto_20190830_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 1, 52, 50, 340125, tzinfo=utc), null=True),
        ),
    ]
