# Generated by Django 2.1.2 on 2019-09-19 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_auto_20190919_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(null=True, upload_to='mysite/static/images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 19, 15, 22, 43, 9919, tzinfo=utc), null=True),
        ),
    ]
