# Generated by Django 2.1.2 on 2019-09-19 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_auto_20190919_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 19, 16, 46, 24, 18065, tzinfo=utc), null=True),
        ),
    ]
