# Generated by Django 2.1.2 on 2019-09-21 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20190920_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='_photo',
            field=models.CharField(default='images/', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 21, 13, 53, 37, 360937, tzinfo=utc), null=True),
        ),
    ]
