# Generated by Django 2.1.2 on 2019-10-15 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190921_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 16, 8, 26, 276638, tzinfo=utc), null=True),
        ),
    ]
