# Generated by Django 2.1.2 on 2019-10-16 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20191016_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 3, 13, 34, 275349, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer_id',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
