# Generated by Django 2.1.2 on 2019-10-16 12:48

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0044_auto_20191016_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='customers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 12, 48, 54, 171045, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit_cards',
            field=models.ManyToManyField(blank=True, to='core.CreditCard'),
        ),
    ]
