# Generated by Django 2.1.2 on 2019-10-16 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20191016_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 12, 48, 59, 344141, tzinfo=utc), null=True),
        ),
    ]
