# Generated by Django 2.1.2 on 2019-10-16 12:57

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20191016_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='supporting_zip_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 12, 57, 36, 758890, tzinfo=utc), null=True),
        ),
    ]
