# Generated by Django 2.1.2 on 2019-10-16 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20191016_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 13, 2, 28, 840090, tzinfo=utc), null=True),
        ),
    ]
