# Generated by Django 2.1.2 on 2019-10-16 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20191016_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 17, 6, 23, 843151, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='customers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
