# Generated by Django 2.1.2 on 2019-10-16 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20191016_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 17, 8, 36, 701142, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_status',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
