# Generated by Django 2.1.2 on 2019-10-16 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20191016_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('vendor_name',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 17, 20, 39, 168288, tzinfo=utc), null=True),
        ),
    ]
