# Generated by Django 2.1.2 on 2019-10-16 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20191016_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor_name',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 17, 22, 44, 334912, tzinfo=utc), null=True),
        ),
    ]
