# Generated by Django 2.1.2 on 2019-10-18 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20191018_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 18, 28, 53, 213052, tzinfo=utc), null=True),
        ),
    ]
