# Generated by Django 2.1.2 on 2019-10-18 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20191018_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='type',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 19, 34, 38, 665333, tzinfo=utc), null=True),
        ),
    ]
