# Generated by Django 2.1.2 on 2019-10-18 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20191018_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 19, 46, 2, 667356, tzinfo=utc), null=True),
        ),
    ]
